# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3af8f55080378f7192f2ffc07d94cb8ac7d4664293f362d9c161e648e0cd0f05213f41ef9bde164ea296df07e7454b26128f61a4ef291f492e3953cfa02f66be

test:
  secret_key_base: 038472ea732fb0942eeb9b21c6157ba8afd15dbbdb398c0bc5b5c2555273effdfe69b478cbda637c8e1a9a5486d118603e3fefd47d5acb06eb84ed086fd9159d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
